---
app:
  jwt:
    expiration-in-minute: 30
    secret: RandomSecretKey123456789!RandomSecretKey123456789!RandomSecretKey123456789!
spring:
  application:
    name: security
  main:
    #Desactivo el Banner de Spring Boot de consola
    banner-mode: off
  datasource:
    url: jdbc:mysql://20.121.214.190:3307/account-db
    username: root
    password: nocountry#2023
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  #Connect kafka
  kafka:
    bootstrap-servers: 20.121.214.190:9092
    template:
      default-topic: account-topic

logging:
  level:
    root: INFO
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

service:
  security:
    secure-key-username: NoCountryKeySecureUsername
    secure-key-password: NoCountryKeySecurePassword!

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    service-url:
      default-zone: https://s10-14-ft-eurekaserver.azurewebsites.net/eureka

resilience4j.retry:
  instances:
    securityRetry:
      max-attempts: 5
      wait-duration: 2000ms
      retry-exceptions:
        - java.io.IOException
        - java.lang.RuntimeException

#resilience4j.circuitbreaker:
  #instances:
    #mysqlCR:
      #registerHealthIndicator: true
      #slidingWindowType: COUNT_BASED
      #slidingWindowSize: 5
      #slow-call-rate-threshold: 30
      #slow-call-duration-threshold: 100s
      #waitDurationInOpenState: 30s
      #failureRateThreshold: 50
      #ignoreExceptions:
        #- java.lang.IllegalArgumentException
        #- s1014ftjavaangular.security.domain.exceptions.AccountAlreadyExists
        #- jakarta.validation.ConstraintViolationException
management:
  tracing:
    sampling:
      probability: 1.0

...
